using Core.Security.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.Security.SeedData
{
    public static class CompanySeedData
    {
        public static List<Company> GetSeedData()
        {
            return new List<Company>()
            {
                new Company{Id=1,Name="Turkcell Global Bilgi",Location="Kocaeli / Türkiye",ImageUrl="/images/job/1.webp",Description="Şirket Hakkında\r\nTurkcell Global Bilgi Hakkında\r\nŞirket Konumu:\r\nBir Turkcell grup şirketi olarak 1999 yılında kurulduğumuzda amacımız hep eşsiz bir müşteri deneyimi yaşatmaktı.\r\n\r\nYıllar geçse de amacımız hiç değişmedi ve bugün biz yine aynı odak noktası ve artan heyecanımızla; toplam 15 lokasyonda, 16 binden fazla çalışanımızla firmaların müşteri deneyimini iyileştirmeye devam ediyoruz.\r\n\r\nTelekom sektöründeki köklü tecrübemizin yanı sıra; finans, sigorta, e-ticaret, perakende, ulaştırma, hızlı tüketim, havacılık, otomotiv, teknoloji, enerji ve kamu sektörlerinde hizmet vermekteyiz.\r\n\r\nEşsiz müşteri deneyimine ulaşabilmek için geleneksel bir kanal olan ve Ana Hizmetlerimizin altında yeralan çağrı hizmetlerimize; Dijital, Teknolojik ve Danışmanlık Hizmetlerimizi de ekleyerek güçlendirdik.\r\n\r\nDaha hızlı, tasarruf sağlayan, kolay ulaşılabilen bir müşteri deneyimi sunmak için RPA (Robotik Süreç Otomasyonu), Dijital Yardım Masası, Social Sniffer, Konuşma Analizi, Bulut Santral, Chat & Chat Bot gibi dijital hizmetlerimizi kullanıyoruz.\r\n\r\nMüşteri deneyimi uçtan uca bir süreç olduğu için; Deneyim Tasarımı, Kalite & Araştırma Yönetimi gibi danışmanlık hizmetlerimiz ile bu deneyimin tasarım aşamasını da analitik bir bakış açısıyla sunuyoruz.\r\n\r\nAna hizmetlerimiz içerisinde yer alan çağrı hizmetlerimizi ise sadece ses kanalı ile vermekle kalmayıp, görüntülü görüşme ve otomatik sesli yanıt sistemleri (IVR) ile destekleyerek müşterilerimize eşsiz bir deneyim yaşatıyoruz.\r\n"},
                new Company{Id=2,Name="GLOBALPBX İLETİŞİM TEKNOLOJİLERİ ANONİM ŞİRKETİ",Location="Ankara / Türkiye",ImageUrl="/images/job/2.webp",Description="GLOBALPBX İLETİŞİM TEKNOLOJİLERİ ANONİM ŞİRKETİ "},
                new Company{Id=3,Name="Panasonic Electric Works Türkiye",Location="İstanbul(Asya) / Türkiye",ImageUrl="/images/job/3.webp",Description="Şirket Hakkında\r\nPanasonic Electric Works Türkiye Hakkında\r\nŞirket Konumu: İstanbul / Türkiye\r\nHakkında \r\n\r\nİnsan odaklı yaklaşımlarla daha iyi ve konforlu bir ‘yaşam’ sunmak için…\r\n\r\nPanasonic Electric Works Türkiye, İstanbul’da yer alan endüstriyel tesislerinde faaliyet göstermekte olup; konfor, güvenlik ve enerji verimliliği sağlayan yenilikçi ürün ve çözümlerini dünya pazarlarına ulaştırmayı ve insan odaklı yaklaşımlarla daha iyi ve konforlu bir ‘yaşam’ sunmayı hedeflemektedir. 2014 yılında gerçekleştirdiği yatırımla birlikte, sektörünün öncü ve “Super Brand” statüsüne sahip markası VİKO’yu da bünyesinde bulunduran Panasonic Electric Works Türkiye, 60’dan fazla ülkeye gerçekleştirdiği ihracat ile markalarını dünya pazarlarında başarıyla temsil etmekte ve Türkiye’deki sektör liderliğini sürdürmektedir.\r\n\r\nTeknolojik dönüşümün gerektirdiği tüm otomasyon ve entegrasyonları başarı ile hayata geçiren endüstriyel tesislere sahip bulunan Panasonic Electric Works Türkiye, yaşam alanlarının konfor ve kalitesinin artırılmasına katkı sağlayan ürün ve çözümlerini Dünya pazarlarına sunmak için ARGE, inovasyon ve tasarım çalışmalarını başarı ile yürütmektedir.\r\n\r\nPanasonic Electric Works Türkiye’nin ürün gamı içerisinde; Elektrik Anahtar ve Prizleri, Grup Prizler, Aksesuarlar, Kablo Kanalları, Alçak Gerilim Şalt Ürünleri, Sigorta Kutuları, Akıllı Ev ve Bina Otomasyon Sistemleri, LED Aydınlatma Ürünleri, Güneş Enerjisi Panelleri ve Yangın Algılama - Alarm Sistemleri yer almaktadır.\r\n\r\nSürdürülebilirliği kurumsal sorumlulukları arasında ele alan ve geleceğe değer katan birçok proje gerçekleştiren Panasonic Electric Works Türkiye; ayrıca kalite, güvenlik ve çevre sorumluluğuna önem veren yaklaşımlarının sonucu olarak ISO 9001, ISO 14001, OHSAS 18001 ve ISO 27001 Bilgi Güvenliği Sistemleri sertifikalarına sahip bulunmaktadır.\r\n\r\nPanasonic Electric Works Türkiye, sektöründe dünyanın lider kuruluşları arasında yer almak ve iş alanlarını genişleterek konforlu ev ve yaşam alanlarına katkı sağlamak için hayata değer katmaya devam edecektir."},
                new Company{Id=4,Name="Samsung",Location="Tekirdağ / Türkiye",ImageUrl="/images/job/4.webp",Description="Samsung Hakkında\r\nŞirket Konumu: Tekirdağ / Türkiye\r\nSamsung, yerel yasa ve yönetmeliklere uyum sağlamanın yanı sıra tüm çalışanlarına katı küresel davranış kuralları uygulama konusunda kararlıdır. Etik yönetimin yalnızca küresel iş ortamındaki hızlı değişikliklere yanıt vermek için bir araç değil, aynı zamanda müşteriler, hissedarlar, çalışanlar, iş ortakları ve yerel topluluklar da dahil olmak üzere çeşitli paydaşları ile güven inşa etmenin bir aracı olduğuna inanmaktadır. Dünyanın en etik şirketlerinden biri olmayı hedefleyen Samsung, adil ve şeffaf kurumsal yönetim uygularken, çalışanlarını eğitmeye ve izleme sistemlerinden faydalanmaya devam eder.\r\n\r\nMisyonumuz ve yaklaşımımız\r\nSamsung, basit bir iş felsefesini uygulamaktadır: yeteneğini ve teknolojisini daha iyi bir küresel topluma katkıda bulunan üstün ürün ve hizmetler yaratmaya adamak. Samsung, bunu başarmak için çalışanlarına ve teknolojilere büyük bir değer verir.\r\n\r\nSamsung’un ruhunu tanımlayan değerler\r\nSamsung, güçlü değerlere göre yaşamanın, iş faaliyetlerinde başarının anahtarı olduğuna inanmaktadır. Bu nedenle, bu temel değerler ve katı davranış kuralları, şirketin verdiği her kararın arkasında yer alır.\r\n\r\nSamsung’un beş iş ilkesi\r\nDünya lideri bir şirket olarak Samsung Electronics, kurumsal sosyal sorumluluğa olan bağlılığının bir ifadesi olarak, 2005 yılında “Samsung’un Beş İş İlkesi”ni duyurdu. Bu ilkeler, yasal ve etik standartlara uyumlu küresel davranış kuralları ve kurumsal sosyal sorumluluklarının yerine getirilmesi için bir temel oluşturur."},
                new Company{Id=5,Name="Google",Location="ABD",ImageUrl="/images/job/5.webp",Description="Google Hakkında\r\nŞirket Konumu: ABD\r\nHakkında\r\nA problem isn't truly solved until it's solved for all. Googlers build products that help create opportunities for everyone, whether down the street or across the globe. Bring your insight, imagination and a healthy disregard for the impossible. Bring everything that makes you unique. Together, we can build for everyone."},
                new Company{Id=6,Name="Büyük Savunma ve Yazılım Teknolojileri A.Ş.",Location="Ankara / Türkiye",ImageUrl="/images/job/6.webp",Description="Şirket Hakkında\r\nBüyük Savunma ve Yazılım Teknolojileri A.Ş. Hakkında\r\nŞirket Konumu:\r\nBüyük Savunma ve Yazılım Teknolojileri A.Ş. teknoloji ve inovasyon alanında uzman kadrosu, yönetim ekibi ve profesyonel danışmanları ile Bilişim Teknolojileri alanında iş ortaklarının tüm ihtiyaçlarınıza sorunsuz ve kaliteli çözümler sunabilmek için 2019 yılında Ankara'da faaliyetlerine başlamıştır.\r\n\r\nBüyük Savunma ve Yazılım Teknolojileri A.Ş. gerçek ve kesintisiz bir arka uç teknoloji ortağıdır ve işinizi ileriye götürmeye odaklanan talep üzerine geliştiricilere sahip, masaüstü, mobil ve web tabanlı uygulamaların geliştirilmesini hızlandırır.\r\n\r\nVizyonumuz; Türkiye'deki Bilişim Teknolojileri ve İnovasyon kültürünün gelişimine doğrudan katkı sağlamak, değişen ve gelişen yenilikçi bütün operasyonların öncüsü ve geliştiricisi olmak, bu değişimi yönlendiren ve geliştiren iş ortaklarımızın çalışma modeli ve standartlarını daha da yukarı çıkarmak, yerli sermaye ve yerli istihdam ile hem çalışanları hem de iş ortaklarının güvenle tercih ettiği, sektörün öncüsü ve lideri bir danışmanlık ve çözüm şirketi olmaktır.\r\n\r\nMisyonumuz; Dünya standartlarında yazılım geliştirme hizmetleri sunmak için yeniliği ve yaratıcılığı öncelikli değer haline getirmek ve müşterilerimizin iş süreçlerinin ya da işlemlerinin verimliliğini artırmak için bu tür mekanizmaları onların talepleri doğrultusunda hayata geçirmek."},
                new Company{Id=7,Name="Hüroğlu Otomotiv San. Tic. A.Ş.",Location="Bursa / Türkiye",ImageUrl="/images/job/7.webp",Description="Hüroğlu Otomotiv San. Tic. A.Ş. Hakkında\r\nŞirket Konumu:\r\n \r\n\r\nHüroğlu Otomotiv San. Tic. A.Ş.\r\n\r\nOtomotiv sektörü için 1972 yılından başlayarak, şu an 6500 m² kapalı, 3000 m² açık alana yayılmış olan çalışma alanıyla, Bursa'da taşıt koltukları üreten Hüroğlu Otomotiv, bu alandaki 36 yıllık deneyimini PULMAN markası ile müşterilerinin hizmetine sunmaktadır.\r\n\r\nHüroğlu Otomotiv A.Ş.'nin otobüs, minibüs, midibüs, tren, metro, kamyon ve gemiler için ürettiği yolcu koltukları, şöför koltukları ve hostes koltukları ülkemizin yanı sıra Orta Doğu, Rusya, Eski Sovyet Cumhuriyetleri, Türki Cumhuriyet, Afrika, Balkan ve Avrupa ülkelerinde güvenle kullanılmaktadır.\r\n\r\nKurulduğu günden bu yana müşteri odaklı bir imalat politikası izleyen Hüroğlu Otomotiv, bünyesinde bulunan AR-GE ve Teknik Hizmet kadroları ile otomotiv endüstrisinin kullandığı en ileri teknolojiye sahip tasarım programlarını kullanarak bir dünya şirketi olma yolunda kararlılıkla ilerlemektedir.\r\n\r\nGenişleyen iç pazar ve ihracat potansiyelini dikkate alarak sürekli olarak büyüme göstermiş olan Hüroğlu Otomotiv bir şirketler grubu haline gelmiş ve bünyesindeki 5 ayrı şirket ile otomotiv sektörünün yanı sıra elektronik ve sigortacılık alanlarında da faaliyet göstermeye başlamıştır.\r\n\r\nPoliüretan ve vakum sanayi alanında faaliyet göstermek üzere HÜRPOL A.Ş.'nin gruba katılmasıyla, üretilen taşıt koltuklarında kullanılan sünger, poliüretan ve ABS malzemeler vakumlama işlemi de grup bünyesinde yapılma başlanmış ve koltuk imalatında entegrasyon sağlanmıştır.\r\n\r\nKaliteyi yalnızca vazgeçilmez bir amaç olarak değil, aynı zamanda bir yaşam biçimi olarak da benimsemiş olan Hüroğlu Otomotiv A.Ş., bu anlayışını ISO-9001:2000 Kalite yönetim sistemi belgesi ile birlikte 1998 yılından bu yana sürdürmektedir.\r\n\r\n\r\n"},
                new Company{Id=8,Name="ByNoGame®",Location="İzmir / Türkiye",ImageUrl="/images/job/8.webp",Description="Şirket Hakkında\r\nByNoGame® Hakkında\r\nŞirket Konumu:\r\nByNoGame\r\nByNoGame Online oyunlarla ilgili bütün ürünleri bulabileceğiniz bir web platformudur.\r\n\r\nTürkiye’de online oyunlarda ürün satın almak isteyenlerin aklına gelen ilk isim, e-pin satın alınacak en iyi adrestir.\r\n\r\nYirmi yıl önce başladığımız yolculukta daima oyuncuların bizden istediklerine kulak verip kendimizi sürekli geliştirerek bugün 2 milyona yakın kullanıcının tercihi olmayı başardık.\r\n\r\n500’den fazla oyun ile yetinmeyip yurt dışı fuarları takip ediyoruz. Oyun dünyasında olup biten tüm yenilikleri, gelişmeleri ilk elden öğrenip müşterilerimize sunmak için... Her gün genişleyen bayi ağımız ile sitemizde yer alan oyunların daha çok sayıda oyuncuya erişmesini sağlıyoruz. Bayimiz olan kafelerde düzenlediğimiz etkinliklerde oyuncularla bir araya geliyoruz ve onları dinleme fırsatı buluyoruz. İşinize değer katıyoruz.\r\n"},
                new Company{Id=9,Name="Casper Bilgisayar Sistemleri A.Ş.",Location="İstanbul(Asya) / Türkiye",ImageUrl="/images/job/9.webp",Description="Şirket Hakkında\r\nCasper Bilgisayar Sistemleri A.Ş. Hakkında\r\nŞirket Konumu:\r\n\r\nTürkiye’ nin teknoloji markası Casper, 1991 yılında, üç bilgisayar mühendisi girişimci tarafından kuruldu. Bugün 34.500 metrekare kapalı alan üzerine kurulu Avrupa ve Orta Doğu’ nun en büyük bilgisayar üretim tesislerinden biri olma özelliğine sahip olan Casper’ da, tüm ürünlerimizin tasarım ve AR&GE süreçlerini kendi mühendislerimiz ile yürütüyoruz. Yıllık 1 milyon adet üretim yapılabilen Casper tesislerinde, 417 kişi istihdam ediliyor. Global çapta rekabet edebilir ürün ve hizmetimizle yerel üretim avantajını birleştirerek, her zaman tüketiciye en iyi çözümleri, ürün gamını ve satış sonrası destek hizmetini sunmak için çalışıyoruz.\r\n"},
                new Company{Id=10,Name="Arvento Mobil Sistemler A.Ş.",Location="Ankara / Türkiye",ImageUrl="/images/job/10.gif",Description="Şirket Hakkında\r\nArvento Mobil Sistemler A.Ş. Hakkında\r\nŞirket Konumu:\r\nARVENTO HAKKINDA\r\n\r\nMobil takip sistemleri ve IoT - M2M çözümleri geliştirip üreten bir teknoloji şirketi olan Arvento, 120.000+ müşterisi ve 1.500.000+ mobil cihaz referansı ile alanında Türkiye’de pazar lideridir ve dünyanın önde gelen çözüm sağlayıcıları arasındadır. Tamamını Türkiye’de geliştirip ürettiği teknolojisini 3 kıtaya ihraç eden Arvento, alanında Arap Yarımadası, Ortadoğu, Kuzey Afrika, Doğu Avrupa ve Bağımsız Devletler Topluluğu bölgelerinin en büyük oyuncusu konumundadır.\r\n\r\nTürkiye’de Pazar Lideri, Dünyanın İlk 5 Şirketinden Biri\r\n1.500.000’un üzerinde cihaz referansı ve 120.000’in üzerindeki müşteri sayısı ile alanında Türkiye’de Pazar Lideri, dünyanın en büyük ilk 5 şirketinden biri.\r\n\r\nMobil Uygulamalar ve IoT-M2M Türkiye’nin 1 Numaralı Şirketi\r\nMobil Uygulamalar ve IoT-M2M alanlarında Türkiye’nin 1 numaralı şirketi.*\r\n\r\nTeknolojide Öncü, Çözümleriyle Lider\r\nYenilikçi yaklaşımı, yaratıcı Ar-Ge ve üretim ekipleriyle alanında dünyadaki en yeni teknolojilere öncülük ediyor. Geliştirdiği çözümler ile dünyada ilklere imza atıyor.\r\n\r\nTürkiye’de Üretiyor, Dünyaya İhraç Ediyor\r\nTamamını Türkiye’de geliştirdiği yazılım ve donanım çözümleriyle, ürünlerini Avrupa, Ortadoğu, Kuzey Afrika ve Orta Asya’ya ihraç ediyor.\r\n\r\nGlobalde ve Yerelde Ödüllendiriliyor\r\nÜrünleri ve projeleriyle Globalde ve Türkiye’de 50’nin üzerinde ödülün sahibi. Kendi kategorisinde “Avrupa’nın En İyi Şirketi”.**\r\n \r\n*Bilişim 500 araştırması 2017 sonuçlarına göre.\r\n**European Business Awards 2014 sonuçlarına göre"},
                new Company{Id=11,Name="İstanbul Okan Üniversitesi",Location="İstanbul(Asya) / Türkiye",ImageUrl="/images/job/11.webp",Description="İstanbul Okan Üniversitesi"},
                new Company{Id=12,Name="Qtech Bilgi Teknolojileri A.Ş.",Location="İzmir / Türkiye",ImageUrl="/images/job/12.webp",Description="Şirket Konumu:\r\nQtech Bilgi Teknolojileri A.Ş."},
            };
        }
    }
}
