using Core.Security.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.Security.SeedData
{
    public static class EventSeedData
    {
        public  static  List<Event> GetSeedData()
        {

            return new List<Event>()
            {
             new Event {Id = Guid.NewGuid(),Title = "Sürdürülebilir Enerji Fikir Maratonu", Description = "Fikirler Enerjiye, Enerji Geleceğe Dönüşsün! 🌍 \r\n\r\nGüney Marmara Kalkınma Ajansı, Bandırma Onyedi Eylül Üniversitesi iş birliği, Enerjisa Üretim ödül sponsorluğuyla düzenlenen Sürdürülebilir Enerji Fikir Maratonu, gençlerin enerji verimliliği ve yenilenebilir enerji alanlarında yenilikçi çözümler geliştirmesini amaçlayan yeni nesil bir Ideathon!\r\n\r\nAlanında uzman eğitmenlerin yer aldığı Bootcampler ile eğitim al," +
             " mentör desteğiyle fikirlerini geliştir, takımınla beraber jüriye sunumunu yap ve ödülleri kap! 🚀 \r\n\r\n⚡Hemen ücretsiz başvur, enerjinle geleceği şekillendir! ",ImageUrl="/images/bootcamp/1.webp", StartDate =DateTime.Parse("2024-12-13"), EndDate =DateTime.Parse("2024-12-15"), ApplicationDeadline=DateTime.Parse("2024-12-08"),ParticipationText="Bootcamp Hakkında\r\n🔎 Fikir Maratonu Süreci: \r\n \r\n📋Başvuru: Başvurunu tamamladıktan sonra fikir geliştirme sürecine dair detaylı bir bilgilendirme" +
             " maili alacaksın. Takımınla birlikte belirtilen yönergeleri takip ederek temel bir fikir oluşturmalı ve bu fikri bizimle paylaşmalısınız. Endişelenme, izleyeceğiniz tüm adımları açıklayan bir rehber, mailde seninle paylaşılacak.\r\n\r\n \r\n\r\n🛠️ Ön Değerlendirme: Başvurular değerlendirilecek ve Sürdürülebilir Enerji ile ilgili en iyi fikirler seçilecek. Bu süreçte fikirlerin yenilikçi ve uygulanabilir olmasına dikkat edilecek.\r\n\r\n \r\n\r\n👩‍🏫 Bootcamp: Seçilen en iyi fikirlerin sahibi olan takımlar," +
             " Bandırma Onyedi Eylül Üniversitesi’nde gerçekleşecek Bootcamp’e davet edilecek. Alanında uzman eğitmenlerden eğitim alarak enerji verimliliği ve yenilenebilir enerji konularında derinlemesine bilgi edinecek ve fikirlerinizi geliştirme şansı yakalayacaksınız.\r\n\r\n \r\n\r\n⚡ Ideathon: Bootcamp sonrası mentör desteğiyle fikirlerinizi detaylandırarak projenizi en iyi haline getireceksiniz. Bu aşama, fikrinizi öne çıkarmak için kritik bir adım!\r\n\r\n \r\n\r\n🎤 Final: Takımınla geliştirdiğin fikrinizi jüri karşısında" +
             " sunacak ve değerlendirme sürecine katılacaksınız.\r\n\r\n \r\n\r\n🎉 Ödül Takdimi: Jürinin seçtiği en iyi 3 takım belirlenen ödüllerle taçlandırılacak!🏆 Ayrıca, Ideathon sürecine katılıp sunum yapan tüm katılımcılar sertifika alacaklar! ✉️\r\n\r\n \r\n\r\nFikir Maratonu Öncelikleri\r\nYalnızca aşağıda yer alan öncelikler doğrultusunda geliştirilen fikirler değerlendirilecektir. \r\n\r\nGüney Marmara Bölgesi’nde yenilenebilir enerji üretim potansiyelinin geliştirilmesi\r\nGüney Marmara Bölgesi’nde enerji verimliliği uygulamalarının" +
             " ve temiz teknoloji kullanımının yaygınlaştırılması\r\nGüney Marmara Bölgesi’nde yenilenebilir enerji alanında ekipman üretiminin ve eğitim kapasitesinin güçlendirilmesi\r\nKimler Katılabilir?\r\nYenilenebilir enerji ve enerji verimliliği konularına ilgi duyan,\r\nYükseköğretim kurumlarının; ön lisans ve lisans düzeyinde 2., 3., 4.sınıflarında okuyan veya yüksek lisans, doktora programında eğitimine devam ediyor olan,\r\nTakım çalışmasına yatkın, yenilikçi fikirler geliştirmek isteyen,\r\n13-14-15 Aralık 2024 tarihlerinde Bandırma’da etkinliğe yüz yüze katılım sağlayabilecek adaylar, bu fikir maratonuna katılabilir!",   CategoryId = 1 },

             new Event {Id = Guid.NewGuid(),Title="Senior Komünite Programı 1.0", Description="Techcareer.net’in Senior Komünite Programı 1.0, senior yazılımcılara özel tasarlanmış webinarlar, workshoplar ve networking fırsatlarıyla dolu bir etkinlik serisi sunuyor. \r\n\r\nSektörde fark yaratacak bu program için başvuru fırsatını kaçırmayın!",ImageUrl="/images/bootcamp/2.webp",StartDate =DateTime.Parse("2024-12-18"),EndDate =DateTime.Parse("2025-01-02"),ApplicationDeadline=DateTime.Parse("2025-01-02"),ParticipationText="Bootcamp Hakkında\r\nTechcareer.net olarak, senior yazılımcılara özel hazırladığımız Senior Komünite Programı başlıyor! Hem sektör bilgilerini artıracak " +
             "hem de kariyer yolculuğunda seni bir adım ileri taşıyacak bir etkinlik serisi düzenliyoruz. Bu programda, uzman konuklarla gerçekleştireceğimiz canlı yayınlar, Senior Workshoplar ve networking odaklı meet-up etkinlikleriyle buluşuyoruz.\r\n\r\n \r\n\r\nAgile ve Scrum Metodolojileri, Bulut Bilişimi, Yazılım Mimarisi ve Tasarımı alanlarında canlı yayınlar, senior yazılımcılara özel workshop ve networking fırsatını yakalayın.  \r\n\r\nKimler Katılabilir?\r\nYazılım kariyerine sağlam bir başlangıç yapmış ve yapmak isteyenler,\r\nAgile (Çevik) yaklaşım ve scrum metodolojisi hakkında bilgi sahibi olmak isteyen herkes,\r\nBulut bilişim alanında kendini geliştirmek isteyenler,\r\nYazılım mimarisi ve tasarımı" +
             " konularında bilgi edinmek isteyenler,\r\nSenior Workshop ile yeni teknolojilerini öğrenerek kendini geliştirmeyi hedefleyenler,\r\nYüz yüze gerçekleşecek meet-up ile profesyonellerle bir araya gelmek isteyenler başvurabilir!\r\nEtkinlik Detayları\r\n🔴 Canlı Yayınlar\r\n🗓️ 18 Aralık Çarşamba, 19.00: Agile ve Scrum Metodolojileri \r\n🗓️ 25 Aralık Çarşamba, 19.00: Bulut Bilişim\r\n🗓️ 8 Ocak Çarşamba, 19.00: Yazılım Mimarisi ve Tasarımı\r\n\r\n \r\n\r\n💻 Workshop\r\n🗓️ 25-26 Ocak, Cumartesi-Pazar: Senior adayların belirlediği, 2 gün sürecek Senior Workshop\r\n\r\n \r\n\r\n✨ Meet-Up\r\n🗓️ 1 Şubat, Cumartesi: Networking Meetup\r\n\r\nKonuklar: Kariyer.net & Techcareer.net müdür üzeri profesyonelleri," +
             " insan kaynakları uzmanları ve Techcareer.net Komünite Ekibi etkinlikte senior adaylarla beraber olacak.\r\nSenior yazılımcılara özel networking imkanı ve eğitimler!",CategoryId=1 },

             new Event {Id = Guid.NewGuid(),Title="Yapay Zekanın Meslekler Üzerindeki Etkisi ", Description="Doğu Anadolu Kalkınma Ajansı, İnnovan Girişimcilik Merkezi ve Van Yüzüncü Yıl Üniversitesi iş birliğiyle düzenlenen bu etkinlikle beraber yapay zeka mesleklerini keşfetmek ve kariyerinize değer katmak için hemen başvurun!\r\n\r\n",ImageUrl="/images/bootcamp/3.webp",StartDate =DateTime.Parse("2024-12-09"),EndDate =DateTime.Parse("2024-12-09"),ApplicationDeadline=DateTime.Parse("2024-12-09"),ParticipationText="Bootcamp Hakkında\r\nYapay zekanın meslekler üzerindeki etkisi etkinliği yapay zeka meslekleri, geleceğin iş kolları ve yapay zeka eğitimi üzerine farkındalık oluşturmayı amaçlıyor." +
             " Yapay zeka ve teknolojinin sunduğu avantajları anlayarak kariyerinizi bu alanda geliştirme şansı yakalayın.\r\n\r\nKimler Katılabilir?\r\nYapay zeka meslekleri ve geleceğin iş kolları hakkında bilgi sahibi olmak isteyen,\r\nTeknolojinin iş dünyasına etkilerini keşfetmek isteyen,\r\nCV hazırlama ve düzenleme konularında kendini geliştirmek isteyen,\r\nTeknolojiye meraklı tüm üniversite öğrencileri katılabilir.\r\n\r\nEtkinlik Detayları\r\n📅 Tarih: 9 Aralık 2024\r\n🕙 Saat: 10:00'da başlayacaktır.\r\n📍 Yer: Van Yüzüncü Yıl Üniversitesi Cengiz Andiç Kültür Merkezi\r\n\U0001f91d İş Birliği: Doğu Anadolu Kalkınma Ajansı, İnnovan ve Van Yüzüncü Yıl Üniversitesi\r\n\r\nOturumlar:\r\nAçılış" +
             " Konuşması\r\nYapay Zeka: Geçmişi, Bugünü ve Yarını\r\nTeknolojide Kariyer Oturumu\r\nPrompt Engineering\r\nZaman ve Stres Yönetimi (Soft Skill)\r\n\r\nWorkshop ve Yarışmalar:\r\nİş Mülakat Simülasyonu ve Özgeçmiş Eğitimi (Oturumlar sırasında ayrı bir lab’de gerçekleşecektir.)\r\nPrompt Engineering Workshop\r\n\r\nKatılım ve Avantajlar:\r\nÜcretsiz Katılım: Tüm üniversite öğrencilerine açık.\r\nSertifika: Etkinlik sonunda katılım belgesi verilecektir.\r\nOnline Kariyer Workshop'u: Katılımcılar, etkinlik sonrası düzenlenecek ücretsiz 5 saatlik online kariyer workshop'una katılma fırsatı yakalayacak. Bu workshop kapsamında özgeçmiş hazırlama ve teknoloji kariyeri konuları işlenecektir.\r\nNetworking Fırsatı: Yapay zeka, teknoloji" +
             " ve kariyer alanında uzman kişilerle tanışma fırsatı.\r\n\r\nGeleceğin meslekleri ve yapay zekanın iş dünyasındaki rolü hakkında bilgi edinmek, kariyerinize değer katmak ve yeni beceriler kazanmak için bu etkinliği kaçırmayın!",CategoryId=1 },

             new Event {Id = Guid.NewGuid(),Title="Unity Masters: Workshop & Game Jam", Description="Unity Workshop ve GameJam Etkinliğine Katıl!\r\n\r\nKendi Oyununu Geliştir, Unity’de 2D ve 3D Oyun Tasarımının Temellerini Öğren!",ImageUrl="/images/bootcamp/4.webp",StartDate =DateTime.Parse("2024-12-22"),EndDate =DateTime.Parse("2024-12-24"),ApplicationDeadline=DateTime.Parse("2024-12-15"),
             ParticipationText="Bootcamp Hakkında\r\nManisa Celal Bayar Üniversitesi Oyun Tasarımı ve Geliştiricileri Topluluğu iş birliğiyle Unity Workshop, katılımcılara Unity ile oyun geliştirme becerilerini öğretmeyi hedefleyen 10 saatlik yoğun bir eğitim programıdır. Workshop sonunda düzenlenecek olan GameJam, katılımcıların edindikleri bilgileri uygulamalı olarak" +
             " deneyimleyebileceği online bir yarışma etkinliğidir.\r\n\r\n GameJam'de, takımlar yaratıcı oyun projeleri geliştirerek, Techcareer.net sponsorluğunda istedikleri alanda bir Bootcamp kazanma şansı elde edecekler. Bu program Unity öğrenmek, oyun tasarımı ve oyun geliştirme dünyasına adım atmak isteyenler için ideal bir fırsatı sunuyor!\r\n\r\nKimler Katılabilir?\r\nUnity " +
             "ve oyun tasarımı konularında bilgi sahibi olmak isteyen,\r\n2D ve 3D oyun geliştirme becerilerini geliştirmeyi hedefleyen,\r\nOyun programlama, animasyon ve grafik tasarım konularında yeteneklerini geliştirmek isteyen,\r\nTakım çalışmasına yatkın tüm üniversite öğrencileri katılabilir.\r\n\r\nEtkinlik Detayları\r\nUnity Workshop ve GameJam\r\n\r\n7-8 Aralık tarihlerinde düzenlenecek " +
             "olan 10 saatlik Unity Workshop’a katılarak, Unity’de oyun geliştirme temellerini öğren ve kendi oyununu yapma yolunda ilk adımı at! Unity Workshop’un sonunda katılımcılar, 20 Aralık akşamı saat 19.00’da online bir GameJam’de buluşacaklar. Takımlar halinde yapılacak bu GameJam’de, her ekip 2-4 kişilik olacak şekilde oyunlarını geliştirecek.\r\n\r\nGameJam sonunda en başarılı ekip, Techcareer.net tarafından sağlanacak, istediği teknolojide bir Bootcamp kazanma şansı elde edecek! Oyun geliştirme becerilerinizi keşfetmek ve teknoloji dünyasında kariyerinize katkı sağlamak için bu heyecan verici etkinliğe katılmayı kaçırmayın.",CategoryId=1 },

             new Event {Id = Guid.NewGuid(),Title=".Net Workshop", Description="Yazılım dünyasında kariyerine sağlam bir adım at!\r\n\r\nÜniversite öğrencilerine özel .Net Workshop’a hemen başvur.",ImageUrl="/images/bootcamp/5.webp",StartDate =DateTime.Parse("2024-12-13"),EndDate =DateTime.Parse("2024-12-15"),ApplicationDeadline=DateTime.Parse("2024-12-08"),ParticipationText="Bootcamp Hakkında\r\n.Net Workshop, Haliç Üniversitesi Girişimcilik ve Pazarlama Kulübü, IEEE İzmir Ekonomi Üniversitesi ve Fırat Üniversitesi Bilişim ve Eğitim Topluluğu (FÜBET) iş birliğiyle hayata geçirilmektedir. " +
             "Yazılım alanında kariyer hedefleyen üniversite öğrencileri için özel olarak tasarlanan bu eğitim, 10 saat sürecek.\r\n\r\nKatılımcılar, .Net teknolojisinin temel prensiplerini öğrenerek yazılım geliştirme süreçlerini daha iyi kavrayacaklar. Eğitim sonunda verilen katılım belgesi ile kariyerlerine değer katabilecek bir belgeye sahip olacaklar.\r\n\r\nKimler Katılabilir?\r\nYazılım kariyerine sağlam bir başlangıç yapmak isteyen, \r\n.Net teknolojilerini öğrenerek kendini geliştirmeyi hedefleyen, \r\nKariyerine yazılım ve teknoloji alanında yön vermek isteyen,\r\nTüm üniversite öğrencileri başvurabilir.\r\n\r\nEtkinlik Detayları\r\nÜniversite " +
             "öğrencilerine özel olarak düzenlenen .Net Workshop, 22-23-24 Aralık tarihlerinde online olarak gerçekleşecek. Toplamda 10 saatlik bu eğitimle .Net framework ve yazılım geliştirme süreçleri ile alakalı kendini geliştireceksin.\r\n\r\nEtkinlik sonunda katılımcılara katılım belgesi verilecektir. Yazılım ve teknoloji alanında kendini geliştirmek isteyen tüm üniversite öğrencilerini bekliyoruz!",CategoryId=1},



             new Event {Id = Guid.NewGuid(),Title="Innovative Chain 6 ", Description="İnovasyon ve vaka analizi temalı bu etkinlikte, iş dünyasının problemlerine yaratıcı çözümler üretme fırsatını yakala! \r\n\r\nHemen başvur ve yerini al.",ImageUrl="/images/hackathon/1.png",StartDate =DateTime.Parse("2024-12-04"),EndDate =DateTime.Parse("2024-12-04"),ApplicationDeadline=DateTime.Parse("2024-12-04"),ParticipationText="Hackathon Hakkında\r\nMarmara Üniversitesi Marmara İnovasyon Kulübü iş birliğiyle Altıncısı düzenlenen Innovative Chain etkinliği, üniversite öğrencilerinin iş dünyasında karşılaşılabilecek sorunları vaka analizi ve vaka çalışması yöntemleriyle çözmelerini sağlayan bir etkinliktir. \r\n\r\nİnovasyon temalı bu program, katılımcılara case study örnekleri üzerinden yaratıcı " +
             "düşünme ve problem çözme becerilerini geliştirme fırsatı sunar. \"Vaka nedir?\" ve \"İnovasyon nedir?\" gibi soruların yanıtlarını bularak, geleceğin iş dünyasına hazırlanabileceğin bir deneyim seni bekliyor.\r\n\r\nKimler Katılabilir?\r\nVaka analizi yaparak problem çözme becerilerini geliştirmek isteyenler,\r\nİnovasyon ve yaratıcı düşünme konularına ilgi duyanlar,\r\nCase study örnekleri ile iş dünyası problemlerine çözüm üretmek isteyenler,\r\nİnovasyon ve vaka çalışmalarıyla kendini geliştirmek isteyen tüm üniversite öğrencileri.\r\n\r\nEtkinlik Detayları\r\n📅 Tarih: 4 Aralık 2024, Çarşamba\r\n📍 Yer: Marmara Üniversitesi İşletme Fakültesi Recep Tayyip Erdoğan Külliyesi  I1-117 No'lu Sınıf\r\n🎯 Hedef Katılımcı Sayısı: 35-40 kişi\r\n👥 Gruplar: 5 kişilik 7-8 grup\r\n\r\nInnovative Chain etkinliği, iş dünyasının problemlerine inovasyon ve vaka çalışması " +
             "temelli yaklaşımlarla çözüm üretmeyi amaçlıyor. Etkinlik boyunca, katılımcılar vaka analizi yöntemleriyle gerçek hayata dair sorunları çözmeyi öğreniyor.\r\n\r\nEtkinlik iki oturum halinde gerçekleştirilecek:\r\n1. Oturum: 12:00 - 14:00\r\n2. Oturum: 15:00 - 17:00\r\n\r\nKatılımcılar, gruplar halinde verilen bir problemi çözmek için 45 dakika süre alacak ve çözüm önerilerini jüriye 7 dakikalık sunumlarla aktaracak. Jüri, sunumları değerlendirerek en iyi analizleri yapan ilk 3 grubu belirleyecek.\r\n\r\nEtkinlik sonunda katılımcılar, vaka çalışması ve inovasyon konularında değerli deneyimler kazanırken, networking fırsatları ve ödüllerle bu eşsiz programdan faydalanacak.",CategoryId=2},

             new Event {Id = Guid.NewGuid(),Title="Yıldız Teknik Üniversitesi: Zihinsel Kıvılcım ", Description="Yıldız Teknik Üniversitesi SPARK-ed iş birliğiyle odaklanma, derin düşünme ve irade gücünü geliştirecek stratejiler öğren! \r\n\r\nKendini keşfet ve geleceğine ilham kat, hemen başvur!",ImageUrl="/images/hackathon/2.webp",StartDate =DateTime.Parse("2024-12-05"),EndDate =DateTime.Parse("2024-12-05"),ApplicationDeadline=DateTime.Parse("2024-12-05"),ParticipationText="Hackathon Hakkında\r\nYıldız Teknik Üniversitesi Davutpaşa Kampüsü'nde SPARK-ed iş birliğiyle düzenlenen Zihinsel Kıvılcım etkinliği, odaklanma sorunu ve yetişkinlerde odaklanma problemi gibi zorluklara yönelik etkili stratejiler sunuyor. Bu etkinlik, katılımcıların derin düşünme ve irade gücü konularında kendilerini geliştirmelerine, odaklanma problemlerinin üstesinden gelmelerine yardımcı olup kendini daha iyi tanımak ve zihinsel gücünü keşfetmek isteyenler için eşsiz bir fırsat sunuyor.\r\n\r\nKimler Katılabilir?\r\nOdaklanma problemi yaşadığını düşünüyorsan,\r\nZihinsel performansını artırmak istiyorsan, \r\nBu etkinlik sana göre. Tüm üniversite öğrencileri bu etkinliğe dahil olabilir. \r\n\r\nEtkinlik Detayları\r\nZihinsel Kıvılcım etkinliği, katılımcılara odaklanma, derin düşünme ve irade gücü gibi konularda değerli stratejiler sunuyor. Kendini keşfetmek ve zihinsel becerilerini geliştirmek isteyen tüm üniversite öğrencilerini etkinliğimize bekliyoruz.\r\n\r\nTarih: 5 Aralık\r\nYer: Yıldız Teknik Üniversitesi Davutpaşa Kampüsü Elektrik - Elektronik Fakültesi Konferans Salonu",CategoryId=2},

             new Event {Id = Guid.NewGuid(),Title="İstanbul Üniversitesi - Cerrahpaşa: Gelişen Teknoloji Günleri'24 ", Description="IEEE İstanbul Üniversitesi - Cerrahpaşa iş birliğiyle Gelişen Teknoloji Günleri'24 başlıyor.\r\n\r\nTeknoloji konferansı, networking ve daha fazlası bu etkinlikte, Hemen Başvur!",ImageUrl="/images/hackathon/3.webp",StartDate =DateTime.Parse("2024-12-11"),EndDate =DateTime.Parse("2024-12-12"),ApplicationDeadline=DateTime.Parse("2024-12-11"),ParticipationText="Hackathon Hakkında\r\nGETEK'24, farklı sektörlerden öncü teknoloji firmalarını bir araya getirerek, en yeni ve en gelişmiş teknolojileri katılımcılarla buluşturmayı hedefleyerek gerçekleşiyor! Teknoloji konferanslarında, teknoloji dünyasındaki en son gelişmeler, yenilikçi teknolojiler ve gelişen teknoloji trendleri üzerine detaylı sunumlar ve oturumlar gerçekleşecek. 11-12 Aralık 2024'te İstanbul Üniversitesi - Cerrahpaşa: Avcılar Kampüsü, Mühendislik Fakültesi: A-Blok Konferans Salonu'nda düzenlenecek olan GETEK'24 teknoloji meraklıları ve profesyoneller için kaçırılmayacak bir fırsat!\r\n\r\nKimler Katılabilir?\r\nGETEK'24 etkinliği, gelişen teknoloji trendlerine ayak uydurmak ve sektör liderleriyle bir araya gelmek isteyen herkes için düzenleniyor! Öğrenciler, mühendisler, yazılımcılar, girişimciler ve teknolojiye ilgi duyan herkes bu etkinliğe katılabilir. Teknoloji firmaları ile tanışmak, yenilikçi çözümleri yakından görmek ve sektördeki en yeni gelişmeleri öğrenmek isteyen herkesi bekliyoruz.",CategoryId=2},

             new Event {Id = Guid.NewGuid(),Title="Karadeniz Teknik Üniversitesi: DevFest Trabzon 2024", Description="Karadeniz Teknik Üniversitesi: GDG on Campus KTU iş birliğiyle DevFest Trabzon 2024 başlıyor.\r\n\r\nTeknoloji konferansı, networking ve daha fazlası bu etkinlikte, Hemen Başvur!",ImageUrl="/images/hackathon/4.webp",StartDate =DateTime.Parse("2024-12-14"),EndDate =DateTime.Parse("2024-12-14"),ApplicationDeadline=DateTime.Parse("2024-12-14"),ParticipationText="Hackathon Hakkında\r\nGoogle DevFest 2024, GDG Trabzon ve GDG on Campus iş birliğiyle 14 Aralık 2024’te gerçekleşecek! Teknoloji dünyasının önde gelen isimlerini bir araya getiren büyük etkinlikte bu yılın odak noktası, yapay zekâ ve Google teknolojileri olacak. Yapay zekâ konuşmaları, interaktif teknoloji atölyeleri ve sürpriz etkinliklerle dolu bu özel gün, teknolojiye ilgi duyan herkes için kaçırılmayacak bir fırsat sunuyor.\r\n\r\nKimler Katılabilir?\r\nGoogle DevFest 2024 etkinliğine, teknolojiye ilgi duyan ve bilet almış herkes katılabilir! İster öğrenci olun, ister profesyonel ya da teknoloji girişimcisi, bu etkinlik 2024 teknoloji etkinlikleri arasında öne çıkanlardan biri. Yapay zekâ etkinlikleri, Google geliştirici etkinlikleri ve yeni teknolojilerle tanışma fırsatı, herkes için ilham verici ve öğretici bir deneyim sunuyor. ",CategoryId=2},

             new Event {Id = Guid.NewGuid(),Title="Eskişehir Teknik Üniversitesi: ESAS'24", Description="Eskişehir Teknik Üniversitesi: Savunma Sanayii ve Teknolojileri Kulübü iş birliğiyle ESAS'24 başlıyor.\r\n\r\nTeknoloji konferansı, networking ve daha fazlası bu etkinlikte, Hemen Başvur!",ImageUrl="/images/hackathon/5.webp",StartDate =DateTime.Parse("2024-12-14"),EndDate =DateTime.Parse("2024-12-15"),ApplicationDeadline=DateTime.Parse("2024-12-14"),ParticipationText="Hackathon Hakkında\r\nEskişehir Savunma Sanayii Zirvesi 2024 (ESAS'24), sektördeki öncü firmaları ve teknoloji meraklılarını bir araya getiriyor. 14-15 Aralık 2024 tarihlerinde Eskişehir Teknik Üniversitesi: Yabancı Diller Yüksek Okulu Konferans Salonu'nda gerçekleşecek olan bu etkinlik, savunma sanayii dünyasındaki en son gelişmeler ve yenilikler üzerine ilham verici konuşmalar ve stant alanlarıyla dolu olacak. Savunma sanayii zirvesi olarak sektördeki en büyük firmaların katılımıyla düzenlenen ESAS'24, teknoloji meraklıları ve profesyoneller için kaçırılmayacak bir fırsat sunuyor.\r\n\r\nKimler Katılabilir?\r\nESAS'24, savunma sanayiine ilgi duyan tüm katılımcılara açık! Öğrenciler, mühendisler, profesyoneller ve sektörde kariyer yapmak isteyenler için bu zirve, sektör liderleri ile tanışma ve firmalar hakkında daha fazla bilgi edinme fırsatı sunuyor. Savunma teknolojilerinin geleceğini merak eden ve bu alanda bilgi sahibi olmak isteyen herkes etkinliğe katılabilir.",CategoryId=2 },



                new Event {Id = Guid.NewGuid(),Title = "Sürdürülebilir Enerji Fikir Maratonu", Description = "Fikirler Enerjiye, Enerji Geleceğe Dönüşsün! 🌍 \r\n\r\nGüney Marmara Kalkınma Ajansı, Bandırma Onyedi Eylül Üniversitesi iş birliği, Enerjisa Üretim ödül sponsorluğuyla düzenlenen Sürdürülebilir Enerji Fikir Maratonu, gençlerin enerji verimliliği ve yenilenebilir enerji alanlarında yenilikçi çözümler geliştirmesini amaçlayan yeni nesil bir Ideathon!\r\n\r\nAlanında uzman eğitmenlerin yer aldığı Bootcampler ile eğitim al," +
             " mentör desteğiyle fikirlerini geliştir, takımınla beraber jüriye sunumunu yap ve ödülleri kap! 🚀 \r\n\r\n⚡Hemen ücretsiz başvur, enerjinle geleceği şekillendir! ",ImageUrl="/images/hiringchallenge/1.webp", StartDate =DateTime.Parse("2024-12-13"), EndDate =DateTime.Parse("2024-12-15"), ApplicationDeadline=DateTime.Parse("2024-12-08"),ParticipationText="Bootcamp Hakkında\r\n🔎 Fikir Maratonu Süreci: \r\n \r\n📋Başvuru: Başvurunu tamamladıktan sonra fikir geliştirme sürecine dair detaylı bir bilgilendirme" +
             " maili alacaksın. Takımınla birlikte belirtilen yönergeleri takip ederek temel bir fikir oluşturmalı ve bu fikri bizimle paylaşmalısınız. Endişelenme, izleyeceğiniz tüm adımları açıklayan bir rehber, mailde seninle paylaşılacak.\r\n\r\n \r\n\r\n🛠️ Ön Değerlendirme: Başvurular değerlendirilecek ve Sürdürülebilir Enerji ile ilgili en iyi fikirler seçilecek. Bu süreçte fikirlerin yenilikçi ve uygulanabilir olmasına dikkat edilecek.\r\n\r\n \r\n\r\n👩‍🏫 Bootcamp: Seçilen en iyi fikirlerin sahibi olan takımlar," +
             " Bandırma Onyedi Eylül Üniversitesi’nde gerçekleşecek Bootcamp’e davet edilecek. Alanında uzman eğitmenlerden eğitim alarak enerji verimliliği ve yenilenebilir enerji konularında derinlemesine bilgi edinecek ve fikirlerinizi geliştirme şansı yakalayacaksınız.\r\n\r\n \r\n\r\n⚡ Ideathon: Bootcamp sonrası mentör desteğiyle fikirlerinizi detaylandırarak projenizi en iyi haline getireceksiniz. Bu aşama, fikrinizi öne çıkarmak için kritik bir adım!\r\n\r\n \r\n\r\n🎤 Final: Takımınla geliştirdiğin fikrinizi jüri karşısında" +
             " sunacak ve değerlendirme sürecine katılacaksınız.\r\n\r\n \r\n\r\n🎉 Ödül Takdimi: Jürinin seçtiği en iyi 3 takım belirlenen ödüllerle taçlandırılacak!🏆 Ayrıca, Ideathon sürecine katılıp sunum yapan tüm katılımcılar sertifika alacaklar! ✉️\r\n\r\n \r\n\r\nFikir Maratonu Öncelikleri\r\nYalnızca aşağıda yer alan öncelikler doğrultusunda geliştirilen fikirler değerlendirilecektir. \r\n\r\nGüney Marmara Bölgesi’nde yenilenebilir enerji üretim potansiyelinin geliştirilmesi\r\nGüney Marmara Bölgesi’nde enerji verimliliği uygulamalarının" +
             " ve temiz teknoloji kullanımının yaygınlaştırılması\r\nGüney Marmara Bölgesi’nde yenilenebilir enerji alanında ekipman üretiminin ve eğitim kapasitesinin güçlendirilmesi\r\nKimler Katılabilir?\r\nYenilenebilir enerji ve enerji verimliliği konularına ilgi duyan,\r\nYükseköğretim kurumlarının; ön lisans ve lisans düzeyinde 2., 3., 4.sınıflarında okuyan veya yüksek lisans, doktora programında eğitimine devam ediyor olan,\r\nTakım çalışmasına yatkın, yenilikçi fikirler geliştirmek isteyen,\r\n13-14-15 Aralık 2024 tarihlerinde Bandırma’da etkinliğe yüz yüze katılım sağlayabilecek adaylar, bu fikir maratonuna katılabilir!",   CategoryId = 3 },

                 new Event {Id = Guid.NewGuid(),Title="Senior Komünite Programı 1.0", Description="Techcareer.net’in Senior Komünite Programı 1.0, senior yazılımcılara özel tasarlanmış webinarlar, workshoplar ve networking fırsatlarıyla dolu bir etkinlik serisi sunuyor. \r\n\r\nSektörde fark yaratacak bu program için başvuru fırsatını kaçırmayın!",ImageUrl="/images/hiringchallenge/2.webp",StartDate =DateTime.Parse("2024-12-18"),EndDate =DateTime.Parse("2025-01-02"),ApplicationDeadline=DateTime.Parse("2025-01-02"),ParticipationText="Bootcamp Hakkında\r\nTechcareer.net olarak, senior yazılımcılara özel hazırladığımız Senior Komünite Programı başlıyor! Hem sektör bilgilerini artıracak " +
             "hem de kariyer yolculuğunda seni bir adım ileri taşıyacak bir etkinlik serisi düzenliyoruz. Bu programda, uzman konuklarla gerçekleştireceğimiz canlı yayınlar, Senior Workshoplar ve networking odaklı meet-up etkinlikleriyle buluşuyoruz.\r\n\r\n \r\n\r\nAgile ve Scrum Metodolojileri, Bulut Bilişimi, Yazılım Mimarisi ve Tasarımı alanlarında canlı yayınlar, senior yazılımcılara özel workshop ve networking fırsatını yakalayın.  \r\n\r\nKimler Katılabilir?\r\nYazılım kariyerine sağlam bir başlangıç yapmış ve yapmak isteyenler,\r\nAgile (Çevik) yaklaşım ve scrum metodolojisi hakkında bilgi sahibi olmak isteyen herkes,\r\nBulut bilişim alanında kendini geliştirmek isteyenler,\r\nYazılım mimarisi ve tasarımı" +
             " konularında bilgi edinmek isteyenler,\r\nSenior Workshop ile yeni teknolojilerini öğrenerek kendini geliştirmeyi hedefleyenler,\r\nYüz yüze gerçekleşecek meet-up ile profesyonellerle bir araya gelmek isteyenler başvurabilir!\r\nEtkinlik Detayları\r\n🔴 Canlı Yayınlar\r\n🗓️ 18 Aralık Çarşamba, 19.00: Agile ve Scrum Metodolojileri \r\n🗓️ 25 Aralık Çarşamba, 19.00: Bulut Bilişim\r\n🗓️ 8 Ocak Çarşamba, 19.00: Yazılım Mimarisi ve Tasarımı\r\n\r\n \r\n\r\n💻 Workshop\r\n🗓️ 25-26 Ocak, Cumartesi-Pazar: Senior adayların belirlediği, 2 gün sürecek Senior Workshop\r\n\r\n \r\n\r\n✨ Meet-Up\r\n🗓️ 1 Şubat, Cumartesi: Networking Meetup\r\n\r\nKonuklar: Kariyer.net & Techcareer.net müdür üzeri profesyonelleri," +
             " insan kaynakları uzmanları ve Techcareer.net Komünite Ekibi etkinlikte senior adaylarla beraber olacak.\r\nSenior yazılımcılara özel networking imkanı ve eğitimler!",CategoryId=3 },

              new Event {Id = Guid.NewGuid(),Title="Yapay Zekanın Meslekler Üzerindeki Etkisi ", Description="Doğu Anadolu Kalkınma Ajansı, İnnovan Girişimcilik Merkezi ve Van Yüzüncü Yıl Üniversitesi iş birliğiyle düzenlenen bu etkinlikle beraber yapay zeka mesleklerini keşfetmek ve kariyerinize değer katmak için hemen başvurun!\r\n\r\n",ImageUrl="/images/hiringchallenge/3.webp",StartDate =DateTime.Parse("2024-12-09"),EndDate =DateTime.Parse("2024-12-09"),ApplicationDeadline=DateTime.Parse("2024-12-09"),ParticipationText="Bootcamp Hakkında\r\nYapay zekanın meslekler üzerindeki etkisi etkinliği yapay zeka meslekleri, geleceğin iş kolları ve yapay zeka eğitimi üzerine farkındalık oluşturmayı amaçlıyor." +
             " Yapay zeka ve teknolojinin sunduğu avantajları anlayarak kariyerinizi bu alanda geliştirme şansı yakalayın.\r\n\r\nKimler Katılabilir?\r\nYapay zeka meslekleri ve geleceğin iş kolları hakkında bilgi sahibi olmak isteyen,\r\nTeknolojinin iş dünyasına etkilerini keşfetmek isteyen,\r\nCV hazırlama ve düzenleme konularında kendini geliştirmek isteyen,\r\nTeknolojiye meraklı tüm üniversite öğrencileri katılabilir.\r\n\r\nEtkinlik Detayları\r\n📅 Tarih: 9 Aralık 2024\r\n🕙 Saat: 10:00'da başlayacaktır.\r\n📍 Yer: Van Yüzüncü Yıl Üniversitesi Cengiz Andiç Kültür Merkezi\r\n\U0001f91d İş Birliği: Doğu Anadolu Kalkınma Ajansı, İnnovan ve Van Yüzüncü Yıl Üniversitesi\r\n\r\nOturumlar:\r\nAçılış" +
             " Konuşması\r\nYapay Zeka: Geçmişi, Bugünü ve Yarını\r\nTeknolojide Kariyer Oturumu\r\nPrompt Engineering\r\nZaman ve Stres Yönetimi (Soft Skill)\r\n\r\nWorkshop ve Yarışmalar:\r\nİş Mülakat Simülasyonu ve Özgeçmiş Eğitimi (Oturumlar sırasında ayrı bir lab’de gerçekleşecektir.)\r\nPrompt Engineering Workshop\r\n\r\nKatılım ve Avantajlar:\r\nÜcretsiz Katılım: Tüm üniversite öğrencilerine açık.\r\nSertifika: Etkinlik sonunda katılım belgesi verilecektir.\r\nOnline Kariyer Workshop'u: Katılımcılar, etkinlik sonrası düzenlenecek ücretsiz 5 saatlik online kariyer workshop'una katılma fırsatı yakalayacak. Bu workshop kapsamında özgeçmiş hazırlama ve teknoloji kariyeri konuları işlenecektir.\r\nNetworking Fırsatı: Yapay zeka, teknoloji" +
             " ve kariyer alanında uzman kişilerle tanışma fırsatı.\r\n\r\nGeleceğin meslekleri ve yapay zekanın iş dünyasındaki rolü hakkında bilgi edinmek, kariyerinize değer katmak ve yeni beceriler kazanmak için bu etkinliği kaçırmayın!",CategoryId=3},

             new Event {Id = Guid.NewGuid(),Title="Unity Masters: Workshop & Game Jam", Description="Unity Workshop ve GameJam Etkinliğine Katıl!\r\n\r\nKendi Oyununu Geliştir, Unity’de 2D ve 3D Oyun Tasarımının Temellerini Öğren!",ImageUrl="/images/hiringchallenge/4.webp",StartDate =DateTime.Parse("2024-12-22"),EndDate =DateTime.Parse("2024-12-24"),ApplicationDeadline=DateTime.Parse("2024-12-15"),
                 ParticipationText="Bootcamp Hakkında\r\nManisa Celal Bayar Üniversitesi Oyun Tasarımı ve Geliştiricileri Topluluğu iş birliğiyle Unity Workshop, katılımcılara Unity ile oyun geliştirme becerilerini öğretmeyi hedefleyen 10 saatlik yoğun bir eğitim programıdır. Workshop sonunda düzenlenecek olan GameJam, katılımcıların edindikleri bilgileri uygulamalı olarak" +
                 " deneyimleyebileceği online bir yarışma etkinliğidir.\r\n\r\n GameJam'de, takımlar yaratıcı oyun projeleri geliştirerek, Techcareer.net sponsorluğunda istedikleri alanda bir Bootcamp kazanma şansı elde edecekler. Bu program Unity öğrenmek, oyun tasarımı ve oyun geliştirme dünyasına adım atmak isteyenler için ideal bir fırsatı sunuyor!\r\n\r\nKimler Katılabilir?\r\nUnity " +
                 "ve oyun tasarımı konularında bilgi sahibi olmak isteyen,\r\n2D ve 3D oyun geliştirme becerilerini geliştirmeyi hedefleyen,\r\nOyun programlama, animasyon ve grafik tasarım konularında yeteneklerini geliştirmek isteyen,\r\nTakım çalışmasına yatkın tüm üniversite öğrencileri katılabilir.\r\n\r\nEtkinlik Detayları\r\nUnity Workshop ve GameJam\r\n\r\n7-8 Aralık tarihlerinde düzenlenecek " +
                 "olan 10 saatlik Unity Workshop’a katılarak, Unity’de oyun geliştirme temellerini öğren ve kendi oyununu yapma yolunda ilk adımı at! Unity Workshop’un sonunda katılımcılar, 20 Aralık akşamı saat 19.00’da online bir GameJam’de buluşacaklar. Takımlar halinde yapılacak bu GameJam’de, her ekip 2-4 kişilik olacak şekilde oyunlarını geliştirecek.\r\n\r\nGameJam sonunda en başarılı ekip, Techcareer.net tarafından sağlanacak, istediği teknolojide bir Bootcamp kazanma şansı elde edecek! Oyun geliştirme becerilerinizi keşfetmek ve teknoloji dünyasında kariyerinize katkı sağlamak için bu heyecan verici etkinliğe katılmayı kaçırmayın.",CategoryId=3},

             new Event {Id = Guid.NewGuid(),Title="Innovative Chain 6 ", Description="İnovasyon ve vaka analizi temalı bu etkinlikte, iş dünyasının problemlerine yaratıcı çözümler üretme fırsatını yakala! \r\n\r\nHemen başvur ve yerini al.",ImageUrl="/images/hiringchallenge/5.webp",StartDate =DateTime.Parse("2024-12-04"),EndDate =DateTime.Parse("2024-12-04"),ApplicationDeadline=DateTime.Parse("2024-12-04"),ParticipationText="Hackathon Hakkında\r\nMarmara Üniversitesi Marmara İnovasyon Kulübü iş birliğiyle Altıncısı düzenlenen Innovative Chain etkinliği, üniversite öğrencilerinin iş dünyasında karşılaşılabilecek sorunları vaka analizi ve vaka çalışması yöntemleriyle çözmelerini sağlayan bir etkinliktir. \r\n\r\nİnovasyon temalı bu program, katılımcılara case study örnekleri üzerinden yaratıcı " +
             "düşünme ve problem çözme becerilerini geliştirme fırsatı sunar. \"Vaka nedir?\" ve \"İnovasyon nedir?\" gibi soruların yanıtlarını bularak, geleceğin iş dünyasına hazırlanabileceğin bir deneyim seni bekliyor.\r\n\r\nKimler Katılabilir?\r\nVaka analizi yaparak problem çözme becerilerini geliştirmek isteyenler,\r\nİnovasyon ve yaratıcı düşünme konularına ilgi duyanlar,\r\nCase study örnekleri ile iş dünyası problemlerine çözüm üretmek isteyenler,\r\nİnovasyon ve vaka çalışmalarıyla kendini geliştirmek isteyen tüm üniversite öğrencileri.\r\n\r\nEtkinlik Detayları\r\n📅 Tarih: 4 Aralık 2024, Çarşamba\r\n📍 Yer: Marmara Üniversitesi İşletme Fakültesi Recep Tayyip Erdoğan Külliyesi  I1-117 No'lu Sınıf\r\n🎯 Hedef Katılımcı Sayısı: 35-40 kişi\r\n👥 Gruplar: 5 kişilik 7-8 grup\r\n\r\nInnovative Chain etkinliği, iş dünyasının problemlerine inovasyon ve vaka çalışması " +
             "temelli yaklaşımlarla çözüm üretmeyi amaçlıyor. Etkinlik boyunca, katılımcılar vaka analizi yöntemleriyle gerçek hayata dair sorunları çözmeyi öğreniyor.\r\n\r\nEtkinlik iki oturum halinde gerçekleştirilecek:\r\n1. Oturum: 12:00 - 14:00\r\n2. Oturum: 15:00 - 17:00\r\n\r\nKatılımcılar, gruplar halinde verilen bir problemi çözmek için 45 dakika süre alacak ve çözüm önerilerini jüriye 7 dakikalık sunumlarla aktaracak. Jüri, sunumları değerlendirerek en iyi analizleri yapan ilk 3 grubu belirleyecek.\r\n\r\nEtkinlik sonunda katılımcılar, vaka çalışması ve inovasyon konularında değerli deneyimler kazanırken, networking fırsatları ve ödüllerle bu eşsiz programdan faydalanacak.",CategoryId=3},

             new Event {Id = Guid.NewGuid(),Title="Yıldız Teknik Üniversitesi: Zihinsel Kıvılcım ", Description="Yıldız Teknik Üniversitesi SPARK-ed iş birliğiyle odaklanma, derin düşünme ve irade gücünü geliştirecek stratejiler öğren! \r\n\r\nKendini keşfet ve geleceğine ilham kat, hemen başvur!",ImageUrl="/images/hiringchallenge/6.webp",StartDate =DateTime.Parse("2024-12-05"),EndDate =DateTime.Parse("2024-12-05"),ApplicationDeadline=DateTime.Parse("2024-12-05"),ParticipationText="Hackathon Hakkında\r\nYıldız Teknik Üniversitesi Davutpaşa Kampüsü'nde SPARK-ed iş birliğiyle düzenlenen Zihinsel Kıvılcım etkinliği, odaklanma sorunu ve yetişkinlerde odaklanma problemi gibi zorluklara yönelik etkili stratejiler sunuyor. Bu etkinlik, katılımcıların derin düşünme ve irade gücü konularında kendilerini geliştirmelerine, odaklanma problemlerinin üstesinden gelmelerine yardımcı olup kendini daha iyi tanımak ve zihinsel gücünü keşfetmek isteyenler için eşsiz bir fırsat sunuyor.\r\n\r\nKimler Katılabilir?\r\nOdaklanma problemi yaşadığını düşünüyorsan,\r\nZihinsel performansını artırmak istiyorsan, \r\nBu etkinlik sana göre. Tüm üniversite öğrencileri bu etkinliğe dahil olabilir. \r\n\r\nEtkinlik Detayları\r\nZihinsel Kıvılcım etkinliği, katılımcılara odaklanma, derin düşünme ve irade gücü gibi konularda değerli stratejiler sunuyor. Kendini keşfetmek ve zihinsel becerilerini geliştirmek isteyen tüm üniversite öğrencilerini etkinliğimize bekliyoruz.\r\n\r\nTarih: 5 Aralık\r\nYer: Yıldız Teknik Üniversitesi Davutpaşa Kampüsü Elektrik - Elektronik Fakültesi Konferans Salonu",CategoryId=3},

             new Event {Id = Guid.NewGuid(),Title="İstanbul Üniversitesi - Cerrahpaşa: Gelişen Teknoloji Günleri'24 ", Description="IEEE İstanbul Üniversitesi - Cerrahpaşa iş birliğiyle Gelişen Teknoloji Günleri'24 başlıyor.\r\n\r\nTeknoloji konferansı, networking ve daha fazlası bu etkinlikte, Hemen Başvur!",ImageUrl="/images/hiringchallenge/7.webp",StartDate =DateTime.Parse("2024-12-11"),EndDate =DateTime.Parse("2024-12-12"),ApplicationDeadline=DateTime.Parse("2024-12-11"),ParticipationText="Hackathon Hakkında\r\nGETEK'24, farklı sektörlerden öncü teknoloji firmalarını bir araya getirerek, en yeni ve en gelişmiş teknolojileri katılımcılarla buluşturmayı hedefleyerek gerçekleşiyor! Teknoloji konferanslarında, teknoloji dünyasındaki en son gelişmeler, yenilikçi teknolojiler ve gelişen teknoloji trendleri üzerine detaylı sunumlar ve oturumlar gerçekleşecek. 11-12 Aralık 2024'te İstanbul Üniversitesi - Cerrahpaşa: Avcılar Kampüsü, Mühendislik Fakültesi: A-Blok Konferans Salonu'nda düzenlenecek olan GETEK'24 teknoloji meraklıları ve profesyoneller için kaçırılmayacak bir fırsat!\r\n\r\nKimler Katılabilir?\r\nGETEK'24 etkinliği, gelişen teknoloji trendlerine ayak uydurmak ve sektör liderleriyle bir araya gelmek isteyen herkes için düzenleniyor! Öğrenciler, mühendisler, yazılımcılar, girişimciler ve teknolojiye ilgi duyan herkes bu etkinliğe katılabilir. Teknoloji firmaları ile tanışmak, yenilikçi çözümleri yakından görmek ve sektördeki en yeni gelişmeleri öğrenmek isteyen herkesi bekliyoruz.",CategoryId=3},

             new Event {Id = Guid.NewGuid(),Title="Eskişehir Teknik Üniversitesi: ESAS'24", Description="Eskişehir Teknik Üniversitesi: Savunma Sanayii ve Teknolojileri Kulübü iş birliğiyle ESAS'24 başlıyor.\r\n\r\nTeknoloji konferansı, networking ve daha fazlası bu etkinlikte, Hemen Başvur!",ImageUrl="/images/hiringchallenge/8.webp",StartDate =DateTime.Parse("2024-12-14"),EndDate =DateTime.Parse("2024-12-15"),ApplicationDeadline=DateTime.Parse("2024-12-14"),ParticipationText="Hackathon Hakkında\r\nEskişehir Savunma Sanayii Zirvesi 2024 (ESAS'24), sektördeki öncü firmaları ve teknoloji meraklılarını bir araya getiriyor. 14-15 Aralık 2024 tarihlerinde Eskişehir Teknik Üniversitesi: Yabancı Diller Yüksek Okulu Konferans Salonu'nda gerçekleşecek olan bu etkinlik, savunma sanayii dünyasındaki en son gelişmeler ve yenilikler üzerine ilham verici konuşmalar ve stant alanlarıyla dolu olacak. Savunma sanayii zirvesi olarak sektördeki en büyük firmaların katılımıyla düzenlenen ESAS'24, teknoloji meraklıları ve profesyoneller için kaçırılmayacak bir fırsat sunuyor.\r\n\r\nKimler Katılabilir?\r\nESAS'24, savunma sanayiine ilgi duyan tüm katılımcılara açık! Öğrenciler, mühendisler, profesyoneller ve sektörde kariyer yapmak isteyenler için bu zirve, sektör liderleri ile tanışma ve firmalar hakkında daha fazla bilgi edinme fırsatı sunuyor. Savunma teknolojilerinin geleceğini merak eden ve bu alanda bilgi sahibi olmak isteyen herkes etkinliğe katılabilir.",CategoryId=3},

             new Event {Id = Guid.NewGuid(),Title="Karadeniz Teknik Üniversitesi: DevFest Trabzon 2024", Description="Karadeniz Teknik Üniversitesi: GDG on Campus KTU iş birliğiyle DevFest Trabzon 2024 başlıyor.\r\n\r\nTeknoloji konferansı, networking ve daha fazlası bu etkinlikte, Hemen Başvur!",ImageUrl="/images/hiringchallenge/9.webp",StartDate =DateTime.Parse("2024-12-14"),EndDate =DateTime.Parse("2024-12-14"),ApplicationDeadline=DateTime.Parse("2024-12-14"),ParticipationText="Hackathon Hakkında\r\nGoogle DevFest 2024, GDG Trabzon ve GDG on Campus iş birliğiyle 14 Aralık 2024’te gerçekleşecek! Teknoloji dünyasının önde gelen isimlerini bir araya getiren büyük etkinlikte bu yılın odak noktası, yapay zekâ ve Google teknolojileri olacak. Yapay zekâ konuşmaları, interaktif teknoloji atölyeleri ve sürpriz etkinliklerle dolu bu özel gün, teknolojiye ilgi duyan herkes için kaçırılmayacak bir fırsat sunuyor.\r\n\r\nKimler Katılabilir?\r\nGoogle DevFest 2024 etkinliğine, teknolojiye ilgi duyan ve bilet almış herkes katılabilir! İster öğrenci olun, ister profesyonel ya da teknoloji girişimcisi, bu etkinlik 2024 teknoloji etkinlikleri arasında öne çıkanlardan biri. Yapay zekâ etkinlikleri, Google geliştirici etkinlikleri ve yeni teknolojilerle tanışma fırsatı, herkes için ilham verici ve öğretici bir deneyim sunuyor. ",CategoryId=3},


             new Event {Id = Guid.NewGuid(),Title=".Net Workshop", Description="Yazılım dünyasında kariyerine sağlam bir adım at!\r\n\r\nÜniversite öğrencilerine özel .Net Workshop’a hemen başvur.",ImageUrl="/images/hiringchallenge/10.webp",StartDate =DateTime.Parse("2024-12-13"),EndDate =DateTime.Parse("2024-12-15"),ApplicationDeadline=DateTime.Parse("2024-12-08"),ParticipationText="Bootcamp Hakkında\r\n.Net Workshop, Haliç Üniversitesi Girişimcilik ve Pazarlama Kulübü, IEEE İzmir Ekonomi Üniversitesi ve Fırat Üniversitesi Bilişim ve Eğitim Topluluğu (FÜBET) iş birliğiyle hayata geçirilmektedir. " +
             "Yazılım alanında kariyer hedefleyen üniversite öğrencileri için özel olarak tasarlanan bu eğitim, 10 saat sürecek.\r\n\r\nKatılımcılar, .Net teknolojisinin temel prensiplerini öğrenerek yazılım geliştirme süreçlerini daha iyi kavrayacaklar. Eğitim sonunda verilen katılım belgesi ile kariyerlerine değer katabilecek bir belgeye sahip olacaklar.\r\n\r\nKimler Katılabilir?\r\nYazılım kariyerine sağlam bir başlangıç yapmak isteyen, \r\n.Net teknolojilerini öğrenerek kendini geliştirmeyi hedefleyen, \r\nKariyerine yazılım ve teknoloji alanında yön vermek isteyen,\r\nTüm üniversite öğrencileri başvurabilir.\r\n\r\nEtkinlik Detayları\r\nÜniversite " +
             "öğrencilerine özel olarak düzenlenen .Net Workshop, 22-23-24 Aralık tarihlerinde online olarak gerçekleşecek. Toplamda 10 saatlik bu eğitimle .Net framework ve yazılım geliştirme süreçleri ile alakalı kendini geliştireceksin.\r\n\r\nEtkinlik sonunda katılımcılara katılım belgesi verilecektir. Yazılım ve teknoloji alanında kendini geliştirmek isteyen tüm üniversite öğrencilerini bekliyoruz!",CategoryId=3},



            };

        }
    }
}
