
#GetAllVideoEducation
GET https://localhost:7122/api/VideoEducation?includeDeleted=true
Accept: application/json

###
#PostAllVideoEducation
POST https://localhost:7122/api/VideoEducation
Accept: application/json,

###
#GetAllVideoEducation
GET https://localhost:7122/api/VideoEducation/1
Accept: application/json
###
#PutAllVideoEducation
PUT https://localhost:7122/api/VideoEducation/1
Accept: application/json

###
#DeleteAllVideoEducation
DELETE https://localhost:7122/api/VideoEducation/1?permanent=false
Accept: application/json

###
#GetAllVideoEducation
GET https://localhost:7122/api/VideoEducation/paginate?pageIndex=1&pageSize=10&includeDeleted=false
Accept: application/json